[package]
name = "pka_site_backend"
version = "0.1.0"
authors = ["Zak <zakmikellides@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
warp = { git = "https://github.com/seanmonstar/warp", version = "0.2", features = ["tls", "compression"] }
pretty_env_logger = "0.3"
tokio = { version = "0.2", features = ["full"] }
log = "0.4"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
serde_with = { version = "1.4", features = ["json"] }
rand = "0.7"
lazy_static = "1.4"
futures = "0.3"
diesel = { version = "1", features = ["r2d2", "sqlite", "chrono", "extras"] }
chrono = { version = "0.4", features = ["serde"] }
float-ord = "0.2"
reqwest = "0.10"
regex = "1"
feed-rs = "0.2"
diesel-derive-newtype = "0.1"
iso8601-duration = "0.1"
libsqlite3-sys = { version = "*", features = ["bundled"] }
