version: '3.8'

services:
  app:
    image: zakism/pka-index-backend:latest
    depends_on:
      - redis
    volumes:
      - ./pka_index_data:/data
    environment:
      - YT_API_KEY=$YT_API_KEY
    ports:
      - "127.0.0.1:1234:1234"
    restart: always

  react-frontend:
    image: zakism/pka-index-frontend:latest
    ports:
      - 127.0.0.1:5678:5678
    restart: always

  redis:
    image: redis:6.2.3-alpine
    ports:
      - "127.0.0.1:6379:6379"
    restart: always

  helper:
    image: alpine
    command: sh -c "echo never > /sys/kernel/mm/transparent_hugepage/enabled"
    privileged: true