version: '3'

services:
  app:
    image: zakism/painkiller-already-index:latest
    depends_on:
      - redis
    environment:
      - YT_API_KEY=$YT_API_KEY
    ports:
      - 127.0.0.1:1234:1234
    restart: always

  redis:
    image: redis:5.0.8-alpine
    ports:
      - 127.0.0.1:6379:6379
    restart: always

  helper:
    image: alpine
    command: sh -c "echo never > /sys/kernel/mm/transparent_hugepage/enabled"
    privileged: true
