name: Deploy

on:
  push:
    paths-ignore:
      - 'README.md'
      - 'nginx.conf'
    branches: [ master ]

jobs:
  build:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Download Sqlite3
        run: sudo apt-get install libsqlite3-dev
      - name: Run tests
        run: cargo test --verbose
      - name: Build and Push to Docker
        uses: docker/build-push-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: zakism/pka-index-backend
          tags: latest
