name: Deploy

on:
  push:
    paths-ignore:
      - 'README.md'
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Download Sqlite3
        run: sudo apt-get install libsqlite3-dev
      - name: Run tests
        run: cargo test --verbose
      - name: Build and Push to Docker
        uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: zakism/pka-index-backend
          tags: latest
#      - name: Deploy and Run Docker image on Server
#        uses: appleboy/ssh-action@v0.0.7
#        with:
#          host: ${{ secrets.HOST }}
#          username: ${{ secrets.USERNAME }}
#          password: ${{ secrets.PASSWORD }}
#          port: ${{ secrets.PORT }}
#          script: |
#            ./update_new.sh
