name: Deploy

on:
  push:
    paths-ignore:
      - 'README.md'
      - 'nginx.conf'
    branches: [ master ]

jobs:
  build:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Download Sqlite3
        run: sudo apt-get install libsqlite3-dev
      - name: Run tests
        run: cargo test --verbose
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1.3.0
      - name: Login to DockerHub
        uses: docker/login-action@v1.9.0
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build and Push to Docker
        uses: docker/build-push-action@v2.5.0
        with:
          file: ./Dockerfile
          push: true
          cache-from: type=registry,ref=zakism/pka-index-backend:latest
          cache-to: type=inline
          tags: zakism/pka-index-backend:latest
