name: Rust

on:
  push:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Download Sqlite3
        run: sudo apt-get install libsqlite3-dev
      - name: Build
        run: cargo build --verbose
      - name: Run tests
        run: cargo test --verbose
        
  deploy:

    runs-on: ubuntu-latest

    steps:
      - name: Build Docker image and push to private Docker Repo
      - uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: zakism/painkiller-already-index
          tags: latest
